---
- assert:
    that:
      - "traefik_acme_email is defined"

- name: Creates directories
  file: path="{{ item }}" owner=root group=root state=directory
  with_items: "{{ traefik_dirs }}"

- name: Create traefik systemd service
  template:
    src: "{{ traefik_systemd_service_template }}"
    dest: "{{ traefik_systemd_service_dest }}"
    owner: root
    group: root
    mode: 0644
  notify:
    - reload systemd daemon
    - restart traefik

- name: Generate traefik config file
  template:
    src: "{{ traefik_template }}"
    dest: "{{ traefik_config_file }}"
    owner: root
    group: root
    mode: 0744
  notify:
    - restart traefik

- stat:
    path: "{{ traefik_binary_path }}"
    checksum_algorithm: "{{ traefik_binary_checksum_algorithm }}"
  register: stat_traefik_binary

- name: Stop service Traefik
  service:
    name: traefik
    state: stopped
  when:
    - stat_traefik_binary.stat.exists
    - stat_traefik_binary.stat.checksum != traefik_binary_checksum

- name: Setup Traefik binary
  get_url:
    url: "{{ traefik_binary_url }}"
    dest: "{{ traefik_binary_path }}"
    owner: root
    group: root
    mode: 0755
    checksum: "{{ traefik_binary_checksum_algorithm }}:{{ traefik_binary_checksum }}"

- name: Ensure traefik service is enabled and running
  service:
    name: "{{ traefik_systemd_service_name }}"
    state: started
    enabled: yes
